import type { GameDefinition, GameSlug } from './types'

export const cssGames: GameDefinition[] = [
  {
    slug: 'toggle-puzzle',
    title: 'Toggle Puzzle',
    route: '/games/toggle-puzzle',
    summary: 'A Lights Out style logic board where native checkboxes create the puzzle state and CSS detects the solved pattern.',
    difficulty: 'Beginner',
    cssFeatures: ['checkbox state', ':has()', 'custom properties', 'grid', 'counter-style labels'],
    controls: ['Pointer', 'Tab', 'Space', 'R reset'],
    status: 'playable',
    supportNotes: ':has() is required for solved-state detection. The board remains usable without animations.',
  },
  {
    slug: 'tic-tac-toe',
    title: 'Tic-Tac-Toe',
    route: '/games/tic-tac-toe',
    summary: 'A two-player 3x3 board using radio groups and CSS win-line selectors instead of JavaScript game logic.',
    difficulty: 'Intermediate',
    cssFeatures: ['radio groups', ':has()', 'sibling selectors', 'CSS win lines', 'form reset'],
    controls: ['Pointer', 'Tab', 'Space', 'R reset'],
    status: 'playable',
    supportNotes: 'CSS detects curated win and draw states. Players alternate manually with O/X choices inside each square.',
  },
  {
    slug: 'memory-cards',
    title: 'Memory Cards',
    route: '/games/memory-cards',
    summary: 'A card matching board where checkboxes flip cards, matched pairs stay highlighted, and CSS tracks progress.',
    difficulty: 'Intermediate',
    cssFeatures: ['checkbox state', ':has()', '3D transforms', 'reduced motion', 'CSS counters'],
    controls: ['Pointer', 'Tab', 'Space', 'R reset'],
    status: 'playable',
    supportNotes: 'The matching rule is CSS-declared for a fixed deck so it remains inspectable and deterministic.',
  },
  {
    slug: 'mine-sweeper',
    title: 'Minesweeper',
    route: '/games/mine-sweeper',
    summary: 'A handcrafted minefield with reveal controls, flag markers, loss state, and CSS-only solved detection.',
    difficulty: 'Advanced',
    cssFeatures: ['checkbox state', ':has()', 'data attributes', 'CSS overlays', 'grid matrix variables'],
    controls: ['Pointer', 'Tab', 'Space', 'R reset'],
    status: 'css-feasible',
    supportNotes: 'This is a finite CSS minefield. It does not generate random boards or recursively flood-fill cells.',
  },
  {
    slug: 'snake',
    title: 'Snake',
    route: '/games/snake',
    summary: 'A CSS-feasible snake board with direction controls, path presets, food states, and collision overlays.',
    difficulty: 'Advanced',
    cssFeatures: ['radio state', ':has()', '@property clock', 'CSS animations', 'grid placement'],
    controls: ['Arrow keys', 'WASD', 'Pointer', 'R reset'],
    status: 'css-feasible',
    supportNotes: 'The snake follows curated path states because CSS cannot persist arbitrary growing body segments over time.',
  },
  {
    slug: 'icy-tower',
    title: 'Icy Tower',
    route: '/games/icy-tower',
    summary: 'A vertical platform climber interpretation with CSS-timed tower motion, jump states, and height milestones.',
    difficulty: 'Advanced',
    cssFeatures: ['radio state', ':has()', 'animation timelines', 'transform layers', 'reduced motion'],
    controls: ['Arrow keys', 'Space', 'Pointer', 'R reset'],
    status: 'css-feasible',
    supportNotes: 'The climb uses CSS state lanes and timing presets rather than mutable physics integration.',
  },
  {
    slug: 'doom',
    title: 'Doom CSS Maze',
    route: '/games/doom',
    summary: 'An original raycaster-style maze tribute with radio-driven rooms, doors, keys, enemies, and weapon states.',
    difficulty: 'Expert',
    cssFeatures: ['radio state', ':has()', '3D transforms', 'perspective', 'CSS overlays', 'form state machine'],
    controls: ['Arrow keys', 'WASD', 'Space', 'Pointer', 'R reset'],
    status: 'css-feasible',
    supportNotes: 'Original lab-made visuals only. Rooms are authored states, not a JavaScript raycasting engine.',
  },
]

export function getCssGame(slug: GameSlug) {
  return cssGames.find((game) => game.slug === slug)
}
